[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "nci-tools"
version = "0.1"
readme = "README.md"
description = "Tools for working with NCI accounting"
